# Workflow name
name: 'Chromatic'

# Event for the workflow
on: push

# List of jobs
jobs:
  chromatic-deployment:
    # Operating System
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: component-library
    # Job steps
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: yarn
        # 👇 Adds Chromatic as a step in the workflow
      - name: Build Storybook
        run: yarn build-storybook # script defined in root ./package.json
      - name: Chromatic Preview
        # uses: chromaui/action@v1
        run: yarn chromatic
        # Chromatic GitHub Action options
        # with:
        #   token: ${{ secrets.GITHUB_TOKEN }}
        #   # 👇 Chromatic projectToken, refer to the manage page to obtain it.
        #   projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}